### ISSUE TITLE
No such file or directory: 'commonWords.txt'

### ISSUE THREAD

**Issue by s3cpat** [akashsara/whatsapp-message-analysis#1]
Ran **analyze.py** and got this error
```
Traceback (most recent call last):
  File "analyze.py", line 141, in <module>
    wordDictionary = getWordFrequency(messageList)
  File "analyze.py", line 46, in getWordFrequency
    wordFile = open('commonWords.txt', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'commonWords.txt'
```

**Comment by akashsara** [comment]
Ah, my bad. I completely forgot to include the common words file here. I've fixed it now. Clone/Download and try again. It should work fine.

Looking at the code now though, I should honestly rework some of it, haha.
