### ISSUE TITLE
help me please

### ISSUE THREAD

**Issue by ghaas0ab** [akashsara/whatsapp-message-analysis#2]
Greetings,

I have some issue when I try run analyze.py . so please help me :)

>[root@master whatsapp-message-analysis]# python3.6 analyze.py 
Traceback (most recent call last):
  File "analyze.py", line 5, in <module>
    import graphs
  File "/home/ghaas0ab/Desktop/whatsapp-chat-analysis/whatsapp-message-analysis/graphs.py", line 2, in <module>
    import matplotlib.pyplot as plt
  File "/usr/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 2374, in <module>
    switch_backend(rcParams["backend"])
  File "/usr/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 207, in switch_backend
    backend_mod = importlib.import_module(backend_name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 1, in <module>
    from . import _backend_tk
  File "/usr/lib64/python3.6/site-packages/matplotlib/backends/_backend_tk.py", line 5, in <module>
    import tkinter as Tk
ModuleNotFoundError: No module named 'tkinter'
>

**Comment by akashsara** [comment]
Hey @ghaas0ab,

Try replacing the following code snippet `import matplotlib.pyplot as plt` with:

```
import matplotlib
matplotlib.use('agg')
import matplotlib.pyplot as plt
```
