### ISSUE TITLE
Another chat format

### ISSUE THREAD

**Issue by lucas-ubm** [akashsara/whatsapp-message-analysis#4]
Hey, 

Thanks for the work you have right here. I think I found a new style that's not supported yet.
3/25/19, 17:14 - username: message.

**Comment by lucas-ubm** [comment]
Just in case this helps, the error message was:

`Traceback (most recent call last):
  File "analyze.py", line 230, in <module>
    driver()
  File "analyze.py", line 200, in driver
    'output/' + file_name + '-time_activity.png'
  File "/graphs.py", line 29, in histogram
    y=list(dictionary.values())
  File "/Users/admin/anaconda3/lib/python3.7/site-packages/seaborn/categorical.py", line 3149, in barplot
    errcolor, errwidth, capsize, dodge)
  File "/Users/admin/anaconda3/lib/python3.7/site-packages/seaborn/categorical.py", line 1608, in __init__
    self.establish_colors(color, palette, saturation)
  File "/Users/admin/anaconda3/lib/python3.7/site-packages/seaborn/categorical.py", line 315, in establish_colors
    lum = min(light_vals) * .6
ValueError: min() arg is an empty sequence`

**Comment by akashsara** [comment]
Hey, pushed some new changes that should add support for the message type you mentioned. Let me know if it still doesn't work!

**Comment by akashsara** [comment]
Closing this. If it doesn't work, feel free to reopen the issue.
